language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install: "pip install -r requirements.txt"
before_script:
#  - "flake8 --ignore=F403 app tests "
#  - "flake8 --ignore=F403 tests "
  - "flake8 --ignore=E501,F403 tests"
  - coverage erase
# command to run tests
script:
  - lettuce tests
#  - coverage run
  - coverage run --omit='*lettuce*,*fuzzywuzzy*' tests/features/steps.py
  - coverage report -m
  - nosetests --with-doctest --with-coverage -s app

