language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install: "pip install -r requirements.txt"
#install: "pip-3.3 install -r requirements.txt"
before_script:
  - "flake8 --ignore=F403 app tests "
#  - coverage erase
# command to run tests
script:
#  - coverage run
#  - lettuce tests
  - nosetests --with-doctest --with-coverage -s app
